name: Lint & Security

on:
  pull_request:
    branches: [ main ]

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript,python'
      - name: Perform CodeQL Scan
        uses: github/codeql-action/analyze@v2

  shell-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wearerequired/shellcheck-action@v1
        with:
          shellcheck_version: '0.9.0'
          files: scripts/*.sh
