name: Deploy to Termux (Controlled)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: echo "Deploy job is protected by environment rules and requires manual approval"
      - name: Upload payload (placeholder)
        run: echo "Deploy would execute here (requires secrets & approval)"
