name: Verify Network & Scripts

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'scripts/**'
      - 'ci/**'

jobs:
  network-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint shell scripts
        uses: ludeeus/action-shellcheck@v1
        with:
          files: 'scripts/*.sh'

      - name: Run connectivity check (dry-run)
        env:
          SERVER_HOST: ${{ secrets.TEST_SERVER_HOST }}
          SERVER_PORT: ${{ secrets.TEST_SERVER_PORT }}
          SERVER_USER: ${{ secrets.TEST_SERVER_USER }}
        run: |
          if [ -z "$SERVER_HOST" ]; then
            echo "No test server configured, skipping network checks."
            exit 0
          fi
          sudo apt-get update -y
          sudo apt-get install -y netcat
          nc -vz "$SERVER_HOST" "$SERVER_PORT" || ( echo "Cannot reach server:$SERVER_HOST:$SERVER_PORT" && exit 1 )
